### ISSUE TITLE
old version of row-highlighter

### ISSUE THREAD

**Issue by hnderson** [magroski/gmail-row-highlighter#1]
I'm not sure why but I have a hard time in the new gmail distinguishing between read and unread rows.
In your information about the add-on, you say that you corrected an error that caused the unread rows to not be highlighted.  Is that still available?  I think that could be perfect for me so that I can distinguish between read and unread.
Thank you
Harold Anderson
rro@pobox.com

**Comment by magroski** [comment]
Yes, this has been fixed
